version: '3.7'
services:
  postgresql_db:
    image: postgres:14
    restart: always
    volumes:
      - ./data/db:/var/lib/posgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db_crud_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - postgresql_db
    links:
      - postgresql_db